name: noso_dart
description: "Implementation of basic cryptographic functions for Noso"
version: 1.2.5
homepage: "https://github.com/Noso-Project/NosoDart"
repository: "https://github.com/Noso-Project/NosoDart"

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  pointycastle: ^3.7.3
  convert: ^3.1.1

license: MIT